### PR TITLE
Make DFT compile with GCC

### PR DESCRIPTION
**Pull request by bmanga**
Fixes some issues preventing dft from compiling on GCC. Tested on gcc 6 & 7.
gcc 6 gives warnings on required alignments, but it still passes the tests (KFR 3.0.9 avx2 64-bit (gcc-6.5.0/linux) +in running on avx2)

### CODE REVIEW

**Comment by acxz** [comment]
@bmanga This PR is giving me build errors on GCC 9.1.

**Comment by bmanga** [comment]
Hi @acxz that seems to be a problem with constant expressions in gcc 9. I have reported the bug and added a workaround.
Let me know if you'd like me to also solve the conflicts or you'd rather deal with them internally :)

**Comment by acxz** [comment]
I tried compiling this branch after your commit, but I am still getting errors.

```
In file included from /home/acxz/vcs/github/bmanga/kfr/tests/generate_data.cpp:11:
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp: In lambda function:
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:136:48: error: expected ‘{’ before ‘->’ token
  136 |     return [=](Args... args) CMT_INLINE_MEMBER -> Ret { return deffn(std::forward<Args>(args)...); };
      |                                                ^~
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp: In function ‘cometa::function<Result(Args ...)> cometa::cdispatch(cometa::cvals_t<T>, cometa::identity<T>, Fn&&, DefFn&&)’:
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:136:54: error: expected ‘;’ before ‘{’ token
  136 |     return [=](Args... args) CMT_INLINE_MEMBER -> Ret { return deffn(std::forward<Args>(args)...); };
      |                                                      ^~
      |                                                      ;
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:136:89: error: ‘args’ was not declared in this scope; did you mean ‘Args’?
  136 |     return [=](Args... args) CMT_INLINE_MEMBER -> Ret { return deffn(std::forward<Args>(args)...); };
      |                                                                                         ^~~~
      |                                                                                         Args
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp: In lambda function:
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:147:38: error: expected ‘{’ before ‘->’ token
  147 |                    CMT_INLINE_MEMBER -> Ret { return fn(cval_t<T, v0>(), std::forward<Args>(args)...); };
      |                                      ^~
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp: In function ‘cometa::function<Result(Args ...)> cometa::cdispatch(cometa::cvals_t<T, v0, values ...>, cometa::identity<T>, Fn&&, DefFn&&)’:
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:147:44: error: expected ‘;’ before ‘{’ token
  147 |                    CMT_INLINE_MEMBER -> Ret { return fn(cval_t<T, v0>(), std::forward<Args>(args)...); };
      |                                            ^~
      |                                            ;
/home/acxz/vcs/github/bmanga/kfr/include/kfr/cometa/function.hpp:147:93: error: ‘args’ was not declared in this scope; did you mean ‘Args’?
  147 |                    CMT_INLINE_MEMBER -> Ret { return fn(cval_t<T, v0>(), std::forward<Args>(args)...); };
      |                                                                                             ^~~~
      |                                                                                             Args
make[2]: *** [tests/CMakeFiles/generate_data.dir/build.make:63: tests/CMakeFiles/generate_data.dir/generate_data.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:380: tests/CMakeFiles/generate_data.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by bmanga** [comment]
That's odd ... It compiles fine for me using  ``` CXX=g++-9 cmake -DENABLE_TESTS=ON ..``` and then running ```make```. Are you passing any other option to cmake?

**Comment by bmanga** [comment]
Ok, it has to do with the macro ```CMT_INLINE_MEMBER``` in Release mode.
In the file ```include/kfr/cident.h``` is very difficult to see what's going on with the conditional macros, but it could be that that macro is not defined in Release mode?

**Comment by dlevin256** [comment]
After additional tests, the code will be merged into KFR. Thank you.

**Comment by acxz** [comment]
Ah sorry for not listing my command, yes I was running in Release mode.
I just tested the latest commit on Release mode with both Clang and GCC and they both work.
Commands:
`cmake -DENABLE_TESTS=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release .. && make` : successful
`cmake -DENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Release .. && make` : successful

**Comment by bmanga** [comment]
@dlevin256  @acxz thanks for picking this up! :)

**Comment by acxz** [comment]
@bmanga should these conflicts be resolved before merging?

**Comment by bmanga** [comment]
@acxz yes, but I thought they were going to be dealt with internally. I can fix them though

**Comment by bmanga** [comment]
For the last commit, there was a problem in a constexpr function (#62 ) which should be fixed properly. I also had to remove a FORCEINLINE attribute on a function that was recursively calling itself (make_fft)

**Comment by acxz** [comment]
@bmanga sorry to ring you up again, but it seems that there are still conflicts.

**Comment by bmanga** [comment]
@acxz done.
@dlevin256 can this be merged in now?

**Comment by acxz** [comment]
@dlevin256 what is your position on this PR? Can it be merged so that #56 can be closed?

**Comment by acxz** [comment]
@dlevin256 Let's provide closure on this PR.

**Comment by dlevin256** [comment]
The PR will be tested and merged in coming days. Sorry for delay.

**Comment by acxz** [comment]
@dlevin256 can you give a specific ETA?

**Comment by dlevin256** [comment]
Merged. Thank you.
Tested on GCC 9.2.1. Works fine.

**Pull request merged**
